ISISComputingGroup/EPICS-isisdae

isisdaeApp/src/exVectorPV.cc

X and Y spectra arrays are now checked for changes and a
monitor is not raised unless they have changed

Don't update monitor timestamp if arrays have not changed

---

isisdaeApp/Db/isisdae.db

https://github.com/ISISComputingGroup/IBEX/issues/1373
Added soft channel record for a PV to ISISDAE IOC for toggling visibility of run title in dataweb dashboard page.
To test:
1. make ISISDAE support folder
2. run IOC
3. caput %MYPVPREFIX%DAE:TITLE:DISPLAY 1 / 0

Ticket1373 add toggle run title display pv

---

isisdaeApp/Db/isisdae.db

https://github.com/ISISComputingGroup/IBEX/issues/1274
Added TCB records to ISISDAE db file.

Ticket1274 time channel settings in dae tab (DB)

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/Makefile
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeTestApp/src/build.mak

WIRING_FILE
DETECTOR_FILE
SPECTRA_FILE
TCB_FILE
PERIOD_FILE
To test:
change wiring tables and check PVS update
See ISISComputingGroup/IBEX#1517

Add additional wiring PVS

---

isisdaeApp/Db/isisdae.db

PV for toggling external display of title added to archive
For https://github.com/ISISComputingGroup/IBEX/issues/1645

added title:display to archiver

---

iocBoot/iocisisdaeTest/st.cmd
isisdaeApp/Db/isisdae.db

Flush run control on begin

---

isisdaeApp/Db/isisdae.db

See ISISComputingGroup/IBEX#1743

Remove forward link back to ED

---

isisdaeApp/src/xml/cluster.xml
isisdaeApp/src/xml/dae_settings_cluster.xml
isisdaeApp/src/xml/run_data_cluster.xml

Updates bundled LabVIEW XML for "TS1 only" choice
See ISISComputingGroup/IBEX#2075

Add   TS1 Only  choice

---

configure/CONFIG_SITE
configure/RELEASE
isisdaeApp/src/Makefile
isisdaeApp/src/isisdaeADDriver.cpp
isisdaeApp/src/isisdaeADDriver.h
isisdaeApp/src/isisdaeInclude.dbd
isisdaeTestApp/src/build.mak

This is in preparation for ZOOM work - test is just to check everything still builds as it is not directly called yet, just referenced
See ISISComputingGroup/IBEX#2100

Link areaDetector into DAE and add template from SIM detector

---

isisdaeApp/Db/Makefile
isisdaeApp/Db/dae3_parallel.db
isisdaeApp/Db/isisdae.db

See https://github.com/ISISComputingGroup/IBEX/issues/2026
To test see https://github.com/ISISComputingGroup/EPICS-ioc/pull/120

Ticket2026: Parallel DAE begin/end

---

isisdaeApp/Db/dae_diag.db
isisdaeApp/src/isisdaeDriver.cpp

Correct return value of number of matched diagnostic spectra - exclude all spectra with number -1 
See ISISComputingGroup/IBEX#2300

Ticket2300 diag spectra match

---

isisdaeApp/Db/dae_diag.db

For ticket https://github.com/ISISComputingGroup/IBEX/issues/2347.
See https://github.com/ISISComputingGroup/ibex_gui/pull/517

Add timer to count down to diable diagnostics

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h

Add PVs to enable and disable a veto at run time
See ISISComputingGroup/IBEX#1704

Add veto enable/disable at run time

---

isisdaeApp/Db/isisdae.db

Add DAE simulation mode to dataweb
https://github.com/ISISComputingGroup/IBEX/issues/2659

Make simulation mode interesting and archived

---

isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

This is to avoid the instrument briefly going into e.g. beginning
when a begin is not possible, the system was behavibng correctly as the
ISISICP would raise an error but the brief in and out of BEGINNING
was confusing for the user
See ISISComputingGroup/IBEX#1332

Check allowed run state transition before trying

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/Makefile
isisdaeApp/src/isisdaeDriver.cpp

Add a catch(...) in case of windows structured exception in detector diagnostics
See ISISComputingGroup/IBEX#2750

Add a catch all for windows SEH

---

isisdaeApp/src/CountsPV.cpp
isisdaeApp/src/SpectrumPV.cc
isisdaeApp/src/isisdaeDriver.cpp

Add extra exception handling
See ISISComputingGroup/IBEX#2750

Add additional exception handling

---

isisdaeApp/src/exPV.cc
isisdaeApp/src/exServer.h

Do single reads via timer thread, this is so they don't hang forever
See ISISComputingGroup/IBEX#2971

Do single reads via the timer thread

---

isisdaeApp/src/isisdaeDriver.cpp

See ISISComputingGroup/IBEX#3129

Make asyn parameters update a bit quicker

---

isisdaeApp/Db/ADisisdae.template
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

Add in support for multiple detector live views, also calculate pixel and total count rates
See ISISComputingGroup/IBEX#3381

Ticket3381 live view

---

isisdaeApp/Db/isisdae.db

Add HRPD intermediate shutter DB records to dae db
https://github.com/ISISComputingGroup/IBEX/issues/3327

Add HRPD intermediate shutter records.

---

isisdaeApp/src/isisdaeDriver.cpp

To test see ISISComputingGroup/IBEX#3485

Fix flushing of additional parameter tables

---

isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

Fix liveview period issue seen on LARMOR
See ISISComputingGroup/IBEX#3557

Fix periods

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

See ISISComputingGroup/IBEX#3627

Set STATETRANS during change operations

---

isisdaeApp/src/SpectrumPV.cc
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h

Raw counts can now be obtained using a :YC axis rather than :Y
See ISISComputingGroup/IBEX#3559

Serve raw counts as YC axis

---

isisdaeApp/Db/ADisisdae.template
isisdaeApp/src/CRPTMapping.cpp
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h
isisdaeApp/src/isisicp.tlh
isisdaeApp/src/isisicp.tli

Add TOF cutoff for integral, and also pixel v TOF display option
See ISISComputingGroup/IBEX#3545

Ticket3545 tof liveview

---

isisdaeApp/Db/ADisisdae.template
isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

See ISISComputingGroup/IBEX#3630

Set max X,Y size from PV rather than st.cmd

---

isisdaeApp/Db/ADisisdae.template
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h

Add in support for liveview with histogram mode
see ISISComputingGroup/IBEX#3479

Ticket3479 loq detector

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

See ISISComputingGroup/IBEX#3693

Re-order transition state monitors and add separate CHANGING PV

---

isisdaeApp/Db/Makefile
isisdaeApp/Db/inst_alias_string_parameters.substitutions
isisdaeApp/Db/inst_alias_string_parameters.template
isisdaeApp/Db/inst_real_parameters.substitutions
isisdaeApp/Db/inst_real_parameters.template
isisdaeApp/Db/inst_string_parameters.substitutions
isisdaeApp/Db/inst_string_parameters.template
isisdaeApp/Db/isisdae.db

See ISISComputingGroup/IBEX#4083

Move PARS to ISISDAE

---

isisdaeApp/src/isisdaeDriver.cpp

Use stack based lock/unlock
See ISISComputingGroup/IBEX#4365

Ticket4365 iris dae hang

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

See ISISComputingGroup/IBEX#4140

Add TITLESP variable

---

configure/RELEASE

Minor changes for EPICS 7 compatibility
See ISISComputingGroup/IBEX#4599
* System builds with existing EPICS 3.15

Minor changes for V7 compilation

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

Added support for "events" and "mevents" as required by muon group.
Redefined existing records pertaining to "counts" to be more intuitive.

Ticket4914 waitfor events

---

isisdaeApp/Db/inst_string_parameters.substitutions

Correct definition of geometry and journal blocks PV (fix typo in #62)

Fix geometry/journal definitions

---

isisdaeApp/Db/inst_string_parameters.substitutions
isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp

See ISISComputingGroup/IBEX#5150

Send current config name to ISISICP

---

configure/RELEASE

Update RELEASE for new areaDetector version
See ISISComputingGroup/IBEX#5031

Update RELEASE for new areaDetector

---

isisdaeApp/Db/isisdae.db

Adds post-begin/post-end hooks for https://github.com/ISISComputingGroup/IBEX/issues/4590

Add hooks for post-begin/post-end actions

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeTestApp/src/build.mak

Refactor code to use a single SEWAIT entry point and so avoid race conditions
See ISISComputingGroup/IBEX#5786

Use single SEWAIT entry point

---

isisdaeApp/src/Makefile
isisdaeApp/src/MonLookupPV.cpp
isisdaeApp/src/MonitorCountsPV.cpp
isisdaeApp/src/MonitorSpectrumPV.cpp
isisdaeApp/src/dae.h
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h
isisdaeApp/src/isisicp.tlh
isisdaeApp/src/isisicp.tli

Fix issue with Monitor lookup PV

Fix lookup using :MON: PVs

---

isisdaeApp/Db/ADisisdae.template

https://github.com/ISISComputingGroup/IBEX/issues/4608
Ticket 4608

Ticket4608 Added test records

---

isisdaeApp/Db/isisdae.db

See ISISComputingGroup/IBEX#7315

Autosave some details so valid if DAE is switched off

---

isisdaeApp/src/NORDPV.cpp
isisdaeApp/src/SpectrumPV.cc
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h

To test:   you need to view a spectrum first in GUI e.g. spectrum 2 period 1 then you can type
```
caget %MYPVPREFIX%DAE:SPEC:1:2:Y:MAX
```

Add Y:MAX PV

---

isisdaeApp/src/Makefile
isisdaeTestApp/src/build.mak

standardlise name for htmltidy
ISISComputingGroup/IBEX#8543

linux build fixes

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h

Using negative period number to skip pause/resume needs icp currently building, but to pass positive period number for pause/change/resume all done in isisicp works now
ISISComputingGroup/ibex_bluesky_core#80

Expose fast period change function

---

isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h

See ISISComputingGroup/IBEX#8486

Remove race condition in change/read title

---

isisdaeApp/Db/isisdae.db

for https://github.com/ISISComputingGroup/WebDashboard/issues/76

Webdash title and users

---

isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

now end() is quicker, need to update run number sooner

Update run number quickly on end
