ISISComputingGroup/EPICS-isisdae

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

Relates to https://github.com/ISISComputingGroup/IBEX/issues/1370
To test:
Make this submodule
Make the iocs
Run build_ioc_startups.py (root of EPICS)
Start your instrument
Go to http://localhost:4812/group?name=INST, and look for the records that have had archive values added in this ticket, e.g. RUNNUMBER, TOTALUAMPS, TITLE, _RBNUMBER

Add the records used by the dataweb to the archive

---

isisdaeApp/src/exPV.cc

To test:
You need to read a DAE value that is updating but not being monitor, so you can have the ibex client running but can't use any value it might display, Assuming it is not displaying any spectra, you can:
start a run
caget a spectrum    IN:DEMO:DAE:SPEC:1:2:C    and check it is increasing each time you read
camonitor a spectrum, check it is increasing
caget a spectrum that is being monitored, check it works
, other than that it doesn't break doing a camonitor on  
See ISISComputingGroup/IBEX#1681

Do not force read on already monitored PV

---

isisdaeApp/src/isisdaeInterface.cpp

Fix representation of e.g. < in titles
To test set a title with e.g. a < character before and after the merge, before merge it should set the title in html escaped form, after merge it will be correct
See ISISComputingGroup/IBEX#1624

Ticket1624 unescape xml title

---

isisdaeApp/src/isisdaeDriver.cpp

This should now update as per raw frames. There isn't a fast
appropriate call like total raw or good frames, but at least it
will now update. There is a wider issue to to this properly,
a method exists to return such information but only works if the
period card is running the periods so doesn't adjust for normal
software periods.
See ISISComputingGroup/IBEX#1759

Fix reporting of period good frames

---

iocBoot/iocisisdaeTest/st.cmd
isisdaeApp/Db/Makefile
isisdaeApp/Db/dae_diag.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInclude.dbd
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h
isisdaeApp/src/variant_utils.cpp
isisdaeApp/src/variant_utils.h
isisdaeTestApp/src/build.mak

This adds a dae_diagnostics.db file containing new PVs to build a diagnostics view from
See ISISComputingGroup/IBEX#1846
You should be able to test by running up the isisdaeTest  IOC though you could also locally modify your  ioc/ISISDAE to load up dae_diagnostics.db as well
Once you write 1 to DIAG:ENABLE:SP arrays of data should appear in the various DIAG:TABLE:* waveforms which match the coloums in the LabVIEW table

Initial run diagnostics implementation

---

iocBoot/iocisisdaeTest/st.cmd
isisdaeApp/Db/isisdae.db

See ISISComputingGroup/IBEX#2104
You also need to merge ISISComputingGroup/EPICS-ioc#135
To test:
* Start up ibex server
* Connect a console to the block archiver       console –M localhost ARBLOCK
* Begin a run – you should see the archiver restart in the console window, but no procserv messages (wait at least 10 seconds)
* Abort the run
To do this you need to make a small edit, the program checks for RUNNING and restarts if that is not found, so change the check to look for something other than RUNNING and it should test the hard restart part
* Edit support/isisdae/db/isisdae.db   and change  the word “RUNNING” to say “xRUNNING” in the xpath PV (note: we are editing  the generated file so do not type make again)
* Restart the DAE IOC so it reloads above file 
* Begin a run – you should …

If archiver fails to reload, force hard restart via procServ

---

isisdaeApp/src/exServer.h

Reduce the scan rate of PVs we're not watching. We can end up creating a lot of these from the GUI so keep the scan rate very low so as to limit the performance impact.
https://github.com/ISISComputingGroup/IBEX/issues/1968
This should have no noticeable affect on the GUI, except that the spectra updates freeze less often.
---

Ticket1968: Reduce scan rate of unmonitored PVs

---

isisdaeApp/Db/isisdae.db

Change RUNSTATE_STR to be a string rather than an alias for the enum
See ISISComputingGroup/IBEX#2537

Change RUNSTATE_STR to be a string

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

This PR removes the "(DAE SIMULATION MODE)" from the title and creates a PV that can be used to detect simulation mode
See ISISComputingGroup/IBEX#628

Remove sim mode on title for IBEX

---

isisdaeApp/src/CountsPV.cpp
isisdaeApp/src/FixedValuePV.cpp
isisdaeApp/src/MonLookupPV.cpp
isisdaeApp/src/NORDPV.cpp
isisdaeApp/src/SpectrumPV.cc
isisdaeApp/src/exPV.cc
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

* All error messages now have CAS: prefix so easier to find in logs
* new IOC command isisdaeShowPCAS()   use e.g.    isisdaeShowPCAS 2   at EPICS prompt
* Implemented asyncIO for some reads, in particular spectra
* changed "count" units to "cnt" so fits in dashboard
* Added better implementation of readFloat64() and readInt32() direct reads but not sure if they were ever used (most DBs are on I/O intr)
See ISISComputingGroup/IBEX#3157

Enable AsyncIO for reads

---

isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeInterface.cpp

Check in dcom mode when calling checkConnection()
See ISISComputingGroup/IBEX#3519

Make checkConnection() check for DCOM

---

isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h

Added initHook so background tasks do not start until IOC is
running, this is to allow record initialisation to complete
and so PVs are available from ISISDAE even if no ISISICP
is present.
See ISISComputingGroup/IBEX#4747

Add initHook to delay background thread startup

---

postbuild/update_dlls.bat

visa build was needed on squish but wasn't there. Before this it only copied the dll if it didn't exist (this was for devs) now it always does it. It should not interfere because the only reason for needing the dll is if the IOC doesn't use dcom in which case it is not an instrument.

always copy needed visa dll into build

---

isisdaeApp/Db/inst_string_parameters.substitutions

Check sample and beamline parameters are available through: `caget -t -S TE:NDLT1208:CS:BLOCKSERVER:SAMPLE_PARS|uzhex` and `caget -t -S TE:NDLT1208:CS:BLOCKSERVER:BEAMLINE_PARS|uzhex` respectively. Check that errors no longer occur on https://github.com/ISISNeutronMuon/InstrumentScripts/pull/45

Adding required sample and beamline parameters

---

isisdaeApp/src/SpectrumPV.cc

Refactor to avoid leak of exVecDestructor in some cases, caused a leak on POLREF as spectra set to look at different periods and in some modes the period would not exist

Fix memory leak for non existent  spectra

---

isisdaeApp/src/exPV.cc
isisdaeApp/src/exServer.cc
isisdaeApp/src/isisdaeDriver.cpp

Use a lower scan priority timer queue for spectrum reading, may help with merlin issue when DAE transfer speed goes slow?
See ISISComputingGroup/IBEX#6560

Async scan

---

isisdaeApp/src/FixedValuePV.cpp
isisdaeApp/src/Makefile
isisdaeApp/src/MonLookupPV.cpp
isisdaeApp/src/NoAlarmPV.cpp
isisdaeApp/src/exPV.cc
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeInclude.dbd

* Add SEVR STAT and UDF fields to data arrays
* Do not slow scan PVs that are not being monitored
* Reduce scan rate on fixed pvs that do not change
* Remove alarm level limits on axis PVs
See ISISComputingGroup/IBEX#7216

Try to stop spectra gettng into alarm or disconnected

---

isisdaeApp/src/exPV.cc

Remove timer cancel to avoid deadlock between casPVI::removeMonitor and casPVI::getExtServer (called by getCAS in a scan)
See ISISComputingGroup/IBEX#7636

Remove timer cancel to avoid deadlock

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/NORDPV.cpp
isisdaeApp/src/SpectrumPV.cc
isisdaeApp/src/dae.h
isisdaeApp/src/dae_isisicpint_dummy.cpp
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h
isisdaeApp/src/isisicp.tlh
isisdaeApp/src/isisicp.tli

See ISISComputingGroup/IBEX#8499
This PR also improves NORD readback behaviour

Add reading of per period uah

---

isisdaeApp/src/NORDPV.cpp
isisdaeApp/src/SpectrumPV.cc

Fix crash if ISISICP has more spectra than ISISDAE. Probably came to light recently when the code was changed to propagate spectrum size changes better, only occured if you set more time channels in isisicp than you specified as the maximum in isisdae

Fix overflow in spectrum size

---

isisdaeApp/src/isisdaeDriver.cpp

Fixed issue reported by @rerpha where frame number can go backwards due to being present in two update loops
```
TE:NDW2932:DAE:GOODFRAMES_PD   2025-03-18 11:23:47.980274 1363
TE:NDW2932:DAE:GOODFRAMES_PD   2025-03-18 11:23:48.135180 1208
TE:NDW2932:DAE:GOODFRAMES_PD   2025-03-18 11:23:48.181539 1369
```

Remove double frames update causing value issues

---

isisdaeApp/Db/isisdae.db
isisdaeApp/src/CountsPV.cpp
isisdaeApp/src/MonitorCountsPV.cpp
isisdaeApp/src/MonitorSpectrumPV.cpp
isisdaeApp/src/SpectrumPV.cc
isisdaeApp/src/exServer.cc
isisdaeApp/src/exServer.h
isisdaeApp/src/isisdaeDriver.cpp
isisdaeApp/src/isisdaeDriver.h
isisdaeApp/src/isisdaeInterface.cpp
isisdaeApp/src/isisdaeInterface.h
isisdaeApp/src/isisicp.tlh
isisdaeApp/src/isisicp.tli

Add reading of CRPT spectra stored by an isisicp update command. These are read using names line CSPEC:1:1:Y rather than SPEC:1:1:Y and their value reflects that loaded from the dae by the last update() or updatestore() operation.
am updated and re-registered isisicp is required

Add crpt spectrum reads via PV
